info/__init__.py
from  flask_sqlalchemy import SQLAlchemy
from flask import Flask, render_template, g
from redis import StrictRedis
from flask_wtf import CSRFProtect
from flask_session import Session
from config import config_dict
import logging
from logging.handlers import RotatingFileHandler
from flask_wtf.csrf import generate_csrf


def creat_log(config_name):
    """记录日志的配置信息"""
    # 设置日志的记录等级
    logging.basicConfig(level=config_dict[config_name].LOG_LEVEL)  # 调试debug级
    # 创建日志记录器，指明日志保存的路径、每个日志文件的最大大小、保存的日志文件个数上限
    file_log_handler = RotatingFileHandler("logs/log", maxBytes=1024 * 1024 * 100, backupCount=10)
    # 创建日志记录的格式 日志等级 输入日志信息的文件名 行数 日志信息
    formatter = logging.Formatter('%(levelname)s %(filename)s:%(lineno)d %(message)s')
    # 为刚创建的日志记录器设置日志记录格式
    file_log_handler.setFormatter(formatter)
    # 为全局的日志工具对象（flask app使用的）添加日志记录器
    logging.getLogger().addHandler(file_log_handler)

db = SQLAlchemy()
redis_store=None#type:StrictRedis
def creat_app(config_name):
    """工厂方法，根据传入的不同信息 创建步同的app"""
    # 创建app对象
    creat_log(config_name)
    app = Flask(__name__)
    # 将信息提交到app
    config_class = config_dict[config_name]
    # 将配置注册到app中
    app.config.from_object(config_class)
    # 创建数据库
    db.init_app(app)
    # 创建redis数据库对象
    global redis_store
    redis_store = StrictRedis(host=config_class.REDIS_HOST, port=config_class.REDIS_PORT, db=config_class.REDIS_NUM,
                              decode_responses=True)
    # 开启csrf 保护机制 开启后端验证
    csrf = CSRFProtect(app)
    # 借助第三方调整Session的储存地址
    Session(app)
    # 注册蓝图
    @app.after_request
    def after_request(response):
        csrf_token = generate_csrf()
        response.set_cookie("csrf_token",csrf_token)
        return response

    # 捕获404
    from info.utils.common import login_user
    @app.errorhandler(404)
    @login_user
    def page_not_found(e):
        """页面找不到引导到同意界面"""
        user = g.user
        return render_template("news/404.html",data = {"user_info":user.to_dict()if user else None})

    from info.moudile.admin import admin_dp
    app.register_blueprint(admin_dp)

    from info.utils.common import do_index_class
    app.add_template_filter(do_index_class,"index_class")

    from info.moudile.proflie import profile_bp
    app.register_blueprint(profile_bp)

    from info.moudile.news import news_dp
    app.register_blueprint(news_dp)
    from info.moudile.index import index_dp
    app.register_blueprint(index_dp)
    from info.moudile.passport import passport_bp
    app.register_blueprint(passport_bp)
    return app

info/moudile/admin/__init__.py
from flask import Blueprint

# 创建蓝图对象
admin_dp=Blueprint("admin",__name__,url_prefix='/admin')

from .views import *

@admin_dp.before_request
def before_request():
    """拦截普通用户进入后台页面"""
    if not request.url.endswith(url_for("admin.admin_login")):
        user_id = session.get("user_id")
        is_admin = session.get("is_admin",False)

        if not user_id or not is_admin:
            return redirect("/")

info/moudile/admin/views.py
import time
from info.utils.image_store import qiniu_image_store
from datetime import datetime, timedelta
from flask import request, g, render_template, current_app, session, redirect, url_for, jsonify

from info import constants, db
from info.models import User, News, Category
from info.utils.common import login_user
from info.utils.response_code import RET
from . import admin_dp

@admin_dp.route('/add_category', methods=["POST"])
def add_category():
    """修改或者添加分类"""

    category_id = request.json.get("id")
    category_name = request.json.get("name")
    if not category_name:
        return jsonify(errno=RET.PARAMERR, errmsg="参数错误")
    # 判断是否有分类id
    if category_id:
        try:
            category = Category.query.get(category_id)
        except Exception as e:
            current_app.logger.error(e)
            return jsonify(errno=RET.DBERR, errmsg="查询数据失败")

        if not category:
            return jsonify(errno=RET.NODATA, errmsg="未查询到分类信息")

        category.name = category_name
    else:
        # 如果没有分类id，则是添加分类
        category = Category()
        category.name = category_name
        db.session.add(category)

    try:
        db.session.commit()
    except Exception as e:
        current_app.logger.error(e)
        db.session.rollback()
        return jsonify(errno=RET.DBERR, errmsg="保存数据失败")
    return jsonify(errno=RET.OK, errmsg="保存数据成功")



@admin_dp.route('/news_category')
def get_news_category():
    """新闻分类管理"""
    categories = Category.query.all()
    categories_dict_list = []
    for category in categories:
        category_dict = category.to_dict()
        categories_dict_list.append(category_dict)
    # 删除最新分类
    categories_dict_list.pop(0)
    data= {
        "categories":categories_dict_list
    }
    return render_template("admin/news_type.html",data = data)

@admin_dp.route('/news_edit_detail', methods=["POST", "GET"])
def news_edit_detail():
    """新闻编辑修改接口"""
    if request.method == "GET":
        news_id = request.args.get("news_id")

        #查询新闻
        news=None
        try:
            news = News.query.get(news_id)
        except Exception as e:
            current_app.logger.error(e)

        news_dict = news.to_dict() if news else None

        # 查询所有分类
        try:
            categories = Category.query.all()
        except Exception as e:
            current_app.logger.error(e)
        # 移除最新分类
        categories.pop(0)
        category_dict_list = []
        for category in categories if categories else []:
            # 分类对象转换成字典
            category_dict = category.to_dict()
            # 添加is_selected=False不选择
            category_dict["is_selected"] = False
            # 6 == 6
            # is_selected=True选择中category对应的分类
            if news.category_id == category.id:
                category_dict["is_selected"] = True
            category_dict_list.append(category_dict)

        data = {
            "news": news_dict,
            "categories": category_dict_list
        }

        return render_template("admin/news_edit_detail.html", data=data)

    # POST请求新闻修改
    #1.获取参数
    news_id = request.form.get("news_id")
    title = request.form.get("title")
    digest = request.form.get("digest")
    content = request.form.get("content")
    index_image = request.files.get("index_image")
    category_id = request.form.get("category_id")
    #2.校验参数
    # 1.1 判断数据是否有值
    if not all([title, digest, content, category_id]):
        return jsonify(errno=RET.PARAMERR, errmsg="参数有误")

    news = None # type:News
    try:
        news = News.query.get(news_id)
    except Exception as e:
        current_app.logger.error(e)
    if not news:
        return jsonify(errno=RET.NODATA, errmsg="未查询到新闻数据")

    #3.逻辑处理
    if index_image:
        # 转换成二进制数据
        index_image_data = index_image.read()
        try:
            image_name = qiniu_image_store(index_image_data)
        except Exception as e:
            current_app.logger.error(e)
            return jsonify(errno=RET.THIRDERR, errmsg="主图片保存到七牛云失败")
        # 有修改图片才保存
        news.index_image_url = constants.QINIU_DOMIN_PREFIX + image_name

    #修改新闻对象
    news.title = title
    news.category_id = category_id
    news.digest = digest
    news.content = content

    try:
        db.session.commit()
    except Exception as e:
        current_app.logger.error(e)
        db.session.rollback()
        return jsonify(errno=RET.DBERR, errmsg="修改新闻对象失败")
    #4.返回值
    return jsonify(errno=RET.OK, errmsg="新闻编辑成功")


@admin_dp.route('/news_edit')
def news_edit():
    """返回新闻列表"""

    page = request.args.get("p", 1)
    keywords = request.args.get("keywords", "")
    try:
        page = int(page)
    except Exception as e:
        current_app.logger.error(e)
        page = 1

    news_list = []
    current_page = 1
    total_page = 1

    try:
        filters = []
        # 如果有关键词
        if keywords:
            # 添加关键词的检索选项
            filters.append(News.title.contains(keywords))

        # 查询
        paginate = News.query.filter(*filters) \
            .order_by(News.create_time.desc()) \
            .paginate(page, constants.ADMIN_NEWS_PAGE_MAX_COUNT, False)

        news_list = paginate.items
        current_page = paginate.page
        total_page = paginate.pages
    except Exception as e:
        current_app.logger.error(e)

    news_dict_list = []
    for news in news_list:
        news_dict_list.append(news.to_basic_dict())

    context = {"total_page": total_page, "current_page": current_page, "news_list": news_dict_list}

    return render_template('admin/news_edit.html', data=context)


@admin_dp.route("/news_review_detail",methods=["POST","GET"])
def news_review_detail():
    """新闻审核页面详情显示"""
    if request.method == "GET":
        news_id = request.args.get("news_id")
        news=None
        try:
            news = News.query.get(news_id)
        except Exception as e:
            current_app.logger.error(e)
        if not news:
            return render_template("admin/news_review_detail.html",errmsg="没有该新闻")
        data = {
            "news":news.to_dict()
        }

        return render_template("admin/news_review_detail.html",data=data)

    news_id = request.json.get("news_id")
    action = request.json.get("action")
    # 校验参数
    if not all([news_id,action]):
         return jsonify(errno=RET.PARAMERR, errmsg="参数错误")
    if action not in ("accept", "reject"):
         return jsonify(errno=RET.PARAMERR, errmsg="action参数错误")
    # 逻辑处理
    news=None
    try:
        news = News.query.get(news_id)
    except Exception as e:
        current_app.logger.error(e)
    if not news:
         return jsonify(errno=RET.NODATA, errmsg="没有该新闻")

    if action == "accept":
        news.status = 0
    else:
        reason = request.json.get("reason")
        if not reason:
            return jsonify(errno=RET.PARAMERR, errmsg="请填写拒绝原因")
        news.reason = reason
        news.status = -1
    try:
        db.session.commit()
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR, errmsg="提交数据库异常")
    return jsonify(errno=RET.OK, errmsg="OK")


@admin_dp.route("news_review")
def news_review():
    """返回待审核新闻列表"""
    p = request.args.get("p",1)
    try:
        p = int(p)
    except Exception as e:
        current_app.logger.error(e)
        p =1

    news_list =[]
    current_page = 1
    total_page = 1
    filter=[News.status !=0 ]
    try:
        paginate=News.query.filter(*filter).order_by(News.create_time.desc()).paginate(p,constants.ADMIN_NEWS_PAGE_MAX_COUNT,False)
        news_list=paginate.items
        current_page = paginate.page
        total_page = paginate.pages
    except Exception as e:
        current_app.logger.error(e)

    news_dict_list=[]
    # 将新闻转化为字典列表
    for news in news_list if news_list else []:
        news_dict_list.append(news.to_dict())
    data = {
        "current_page":current_page,
        "total_page":total_page,
        "news_list":news_dict_list
    }
    return render_template("admin/news_review.html",data=data)

@admin_dp.route('/user_list')
@login_user
def user_list():
    """用户列表展示"""
    #1.获取参数
    p = request.args.get("p" ,1)
    user = g.user
    try:
        p= int(p)
    except Exception as e:
        current_app.logger.error(e)
        p =1
    user_list = []
    current_page = []
    total_page= []
    if user:
        try:
            paginate = User.query.filter(User.is_admin == False).\
               paginate(p, constants.ADMIN_USER_PAGE_MAX_COUNT, False)
            user_list = paginate.items
            current_page = paginate.page
            total_page = paginate.pages
        except Exception as e:
            current_app.logger.error(e)
    user_dict_list = []
    for user in user_list if user_list else []:
        user_dict_list.append(user.to_admin_dict())

    data = {
        "users":user_dict_list,
        "current_page" : current_page,
        "total_page":total_page
    }
#     返回值
    return render_template("admin/user_list.html",data= data)



@admin_dp.route('/user_count')
def user_count():
# 查询总人数
    total_count = 0
    try:
        # 10001
        total_count = User.query.filter(User.is_admin == False).count()
    except Exception as e:
        current_app.logger.error(e)

    # 查询月新增数
    mon_count = 0
    try:
        # 2018-8-31号
        now = time.localtime()
        # 2018-08-01月初  2018-09-01
        mon_begin = '%d-%02d-01' % (now.tm_year, now.tm_mon)
        # 使用strptime将字符串转成时间date格式 '%Y-%m-%d'
        mon_begin_date = datetime.strptime(mon_begin, '%Y-%m-%d')
        # 用户的创建时间 > 每一个月的第一天 -->每一个月的新增人数
        mon_count = User.query.filter(User.is_admin == False, User.create_time >= mon_begin_date).count()
    except Exception as e:
        current_app.logger.error(e)

    # 查询日新增数
    day_count = 0
    try:
        # 2018-08-31-0:0
        day_begin = '%d-%02d-%02d' % (now.tm_year, now.tm_mon, now.tm_mday)
        day_begin_date = datetime.strptime(day_begin, '%Y-%m-%d')

info/moudile/index/__init__.py
from flask import Blueprint

# 创建蓝图对象
index_dp=Blueprint("index",__name__)

from .views import *

info/moudile/index/views.py
import logging
from flask import session, current_app, render_template, request, jsonify, g
from info.models import User, News, Category
from info.utils.response_code import RET
from . import index_dp
from info import redis_store, constants
from info import models
from info.utils.common import login_user


@index_dp.route("/news_list")
def news_list():
    """新闻首页显示"""
    """
    1.获取参数
    2.校验参数
    3.逻辑处理
    4.返回值处理
    
    """
#     获取参数
    params_dict= request.args
    page = params_dict.get("page",1)
    per_page = params_dict.get("per_page",constants.HOME_PAGE_MAX_NEWS)
    category_id = params_dict.get("cid",)
#     校验参数
    try:
        page =int(page)
        per_page = int(per_page)
        category_id = int(category_id)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.PARAMERR, errmsg="参数错误")
#     逻辑处理
    filters = [News.status == 0]
    if category_id !=1:
        filters.append(News.category_id==category_id)
    try:
        paginate = News.query.filter(*filters).order_by(News.create_time.desc()).paginate(page, per_page, False)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR, errmsg="查询数据库异常")
    items = paginate.items
    total_page = paginate.pages
    current_page = paginate.page

    news_list = []
    for news in items if items else []:
        news_list.append(news.to_dict())

    data = {
        "newsList":news_list,
        "current_page":current_page,
        "total_page":total_page
    }

    return jsonify(errno=RET.OK, errmsg="查询新闻列表成功" ,data =data)



# 127.0.0.1:5000/
@index_dp.route("/")
@login_user
def index():
    # 通过session去获取用户
    user = g.user

    # -------获取点击排行数据
    news_list =[]
    try:
        news_list=News.query.order_by(News.clicks.desc()).limit(constants.CLICK_RANK_MAX_NEWS)
    except Exception as e:
        current_app.logger.error(e)

    click_news_list = []
    for news in news_list if news_list else []:
        click_news_list.append(news.to_dict())

    # ----新闻分类---

    # 获取新闻分分类数据
    categories = Category.query.all()

    categories_dict=[]
    for category in categories if categories else []:
        categories_dict.append(category.to_dict())


    data= {
        "user_info":user.to_dict() if user else None ,
        "click_news_list":click_news_list,
        "categories":categories_dict
    }
    # 没有调整之前 session数据存储到服务器中
    # redis_store.set("name","wang")
    # session["name"]="James"
    # logging.debug("debug 日志信息")
    # logging.info("info日志信息")
    # logging.warning("waring 日志信息")
    # logging.error("error 日志信息")
    # current_app.logger.debug("rizhi")

    return render_template("index.html",data =data)


@index_dp.route("/favicon.ico")
def favicon():
    """返回图标"""
    return current_app.send_static_file("news/favicon.ico")

info/moudile/news/__init__.py
from flask import Blueprint

# 创建蓝图对象
news_dp=Blueprint("news",__name__,url_prefix="/news")

from .views import *

info/moudile/passport/__init__.py
from flask import Blueprint

passport_bp = Blueprint("passport_bp","name",url_prefix="/passport")

from .views import *

info/moudile/proflie/__init__.py
from flask import Blueprint

profile_bp = Blueprint("profile",__name__,url_prefix="/user")

from .views import *

info/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block titleBlock %}默认标题{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="../static/news/css/reset.css">
    <link rel="stylesheet" type="text/css" href="../static/news/css/main.css">
    <script type="text/javascript" src="../static/news/js/jquery-1.12.4.min.js"></script>
    <script type="text/javascript" src="../static/news/js/main.js"></script>
    {% block scriptBlock %}{% endblock %}
</head>
<body>
    <div class="header_con">
        <div class="header">
            <a href="{{ url_for("index.index")}}" class="logo fl"><img src="../static/news/images/logo.png" alt="logo"></a>
            {% block menuBlock %}{% endblock %}

            {% if data.user_info %}
            <div class="user_login fr">
                <img src="{% if data.user_info.avatar_url %}{{ data.user_info.avatar_url }}{% else %}../../static/news/images/person01.png{% endif %}" class="lgin_pic">
                <a id="nick_name" href="{{ url_for("profile.user_info") }}">{{ data.user_info.nick_name }}</a>
                <a href="javascript:;" onclick="logout()">退出</a>
            </div>
            {% else %}
             <div class="user_btns fr">
                <a href="javascript:;" class="login_btn">登录</a> / <a href="javascript:;" class="register_btn">注册</a>
             </div>
            {%  endif %}

            <!-- 用户登录后显示下面，隐藏上面 -->

        </div>
    </div>

    <div class="conter_con">
        {% block conterBlock %}
        {% endblock %}
        <div class="rank_con fr">
        {% block autherBlock %}
        {% endblock %}
        {% block rankBlock %}
                <div class="rank_title">
                <h3>点击排行</h3>
            </div>
             <ul class="rank_list">
                {% for news in data.click_news_list %}
                    <li><span class="{{ loop.index|index_class}}">{{ loop.index }}</span><a href="/news/{{ news.id }}">{{ news.title }}</a></li>
                {% endfor %}
             </ul>
        {% endblock %}

        </div>
    </div>
    {% block footerBlock %}
    <div class="footer">
        <div class="footer_links">
            <a href="">关于我们</a>
            <span>|</span>
            <a href="">联系我们</a>
            <span>|</span>
            <a href="">招聘人才</a>
            <span>|</span>
            <a href="">友情链接</a>
        </div>
        <p class="copyright">
            CopyRight © 2018 新经资讯信息技术有限公司 All Rights Reserved<br />
电话：010-****888    京ICP备*******8号
        </p>
    </div>
    {% endblock %}


    <!-- 登录表单 -->
    <form class="login_form_con">
        <div class="login_form">
            <div class="login_title">
                <h3>登 录</h3>
                <a href="javascript:;" class="shutoff"></a>
            </div>
            <div class="form_group">
                <input id="mobile" type="text" name="mobile" autocomplete="off">
                <div class="input_tip">手机号</div>
                <div id="login-mobile-err" class="error_tip">手机号不能为空</div>
            </div>
            <div class="form_group">
                <input id="password" type="password" name="password">
                <div class="input_tip">密码(不少于6位)</div>
                <div id="login-password-err" class="error_tip">密码不能为空</div>
            </div>
            <input type="submit" name="" value="登 录" class="input_sub">
            <div class="down_link">还没有账号？<a href="javascript:;" class="to_register">立即注册</a></div>
        </div>
        <div class="mask"></div>
    </form>

    <!-- 注册表单 -->
    <form class="register_form_con">
        <div class="register_form">
            <div class="register_title">
                <h3>注 册</h3>
                <a href="javascript:;" class="shutoff"></a>
            </div>
            <div class="form_group">
                <input type="text" name="mobile" autocomplete="off" id="register_mobile" class="phone_input">
                <div class="input_tip">手机号</div>
                <div id="register-mobile-err" class="error_tip">手机号不能为空</div>
            </div>
            <div class="form_group">
                <input type="text" name="code_pwd" id="imagecode" class="code_pwd">
                <div class="input_tip">图形验证码</div>
                <img src="../static/news/images/pic_code.png" class="get_pic_code" onclick="generateImageCode()">
                <div id="register-image-code-err" class="error_tip">图形码不能为空</div>
            </div>
            <div class="form_group">
                <input type="text" name="smscode" id="smscode" class="code_pwd">
                <div class="input_tip">手机验证码</div>
                <a href="javascript:;" class="get_code" onclick="sendSMSCode()">点击获取验证码</a>
                <div id="register-sms-code-err" class="error_tip">验证码不能为空</div>
            </div>
            <div class="form_group">
                <input type="password" name="password" id="register_password" class="pass_input">
                <div class="input_tip">密码(不少于6位)</div>
                <div id="register-password-err" class="error_tip">密码不能为空</div>
            </div>
            <div  class="form_group2 clearfix">
                <input type="checkbox" class="agree_input" checked>
                <p>同意使用条款，并已阅读"跟帖评论自律管理承诺书"</p>
                <div class="error_tip">请勾选</div>
            </div>
            <input type="submit" name="" value="注 册" class="input_sub">
            <div class="down_link">已有账号？<a href="javascript:;" class="to_login">立即登录</a></div>
        </div>
        <div class="mask"></div>
    </form>
</body>
</html>

info/templates/index.html
{% extends "base.html" %}
{% block titleBlock %}
首页-新经资讯
{% endblock %}
{% block scriptBlock %}
<script type="text/javascript" src="../static/news/js/index.js"></script>
{% endblock %}
{% block conterBlock %}
<ul class="list_con fl">
            <li>
                <a href="#" class="news_pic fl"><img src="../static/news/images/news_pic.jpg"></a>
                <a href="#" class="news_title fl">日本史上最大IPO之一要来了：软银计划将手机业务分拆上市软银计划将手机业务分拆上市</a>
                <a href="#" class="news_detail fl">据日经新闻网，软银计划让旗下核心业务移动手机部门SoftBank Corp.分拆上市，或募资2万亿日元(约180亿美元)。随着软银逐步向投资公司转型，此举旨在给手机业务部门更多自主权。</a>
                <div class="author_info fl">
                    <div class="author fl">
                        <img src="../static/news/images/person.png" alt="author">
                        <a href="#">乐鸣</a>
                    </div>
                    <div class="time fl">2017-01-01 00:00:00</div>
                </div>
            </li>
            <li>
                <a href="#" class="news_pic fl"><img src="../static/news/images/news_pic.jpg"></a>
                <a href="#" class="news_title fl">日本史上最大IPO之一要来了：软银计划将手机业务分拆上市</a>
                <a href="#" class="news_detail fl">据日经新闻网，软银计划让旗下核心业务移动手机部门SoftBank Corp.分拆上市，或募资2万亿日元(约180亿美元)。随着软银逐步向投资公司转型，此举旨在给手机业务部门更多自主权。</a>
                <div class="author_info fl">
                    <div class="source fl">
                        来源：广州日报
                    </div>
                    <div class="time fl">2017-01-01 00:00:00</div>
                </div>
            </li>
            <li>
                <a href="#" class="news_pic fl"><img src="../static/news/images/news_pic.jpg"></a>
                <a href="#" class="news_title fl">日本史上最大IPO之一要来了：软银计划将手机业务分拆上市</a>
                <a href="#" class="news_detail fl">据日经新闻网，软银计划让旗下核心业务移动手机部门SoftBank Corp.分拆上市，或募资2万亿日元(约180亿美元)。随着软银逐步向投资公司转型，此举旨在给手机业务部门更多自主权。</a>
                <div class="author_info fl">
                    <div class="author fl">
                        <img src="../static/news/images/person.png" alt="author">
                        <a href="#">乐鸣</a>
                    </div>
                    <div class="time fl">2017-01-01 00:00:00</div>
                </div>
            </li>
            <li>
                <a href="#" class="news_pic fl"><img src="../static/news/images/news_pic.jpg"></a>
                <a href="#" class="news_title fl">日本史上最大IPO之一要来了：软银计划将手机业务分拆上市</a>
                <a href="#" class="news_detail fl">据日经新闻网，软银计划让旗下核心业务移动手机部门SoftBank Corp.分拆上市，或募资2万亿日元(约180亿美元)。随着软银逐步向投资公司转型，此举旨在给手机业务部门更多自主权。</a>
                <div class="author_info fl">
                    <div class="source fl">
                        来源：广州日报
                    </div>
                    <div class="time fl">2017-01-01 00:00:00</div>
                </div>
            </li>
        </ul>
{% endblock %}
{% block menuBlock %}
<ul class="menu fl">
                {% for category in data.categories %}
                    <li class="{% if category.id == 1 %}active{% endif %}" data-cid="{{ category.id }}"><a href="javascript:;">{{ category.name }}</a></li>
                {% endfor %}
            </ul>
{% endblock %}